# -*- coding: utf-8 -*-
"""Proyecto2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVcUj_CLBhjgTwwNesStdllx-C8jmPj8
"""

def Not (a):
  if (a == 1):
    return 0
  else:
    return 1

def And (a,b):
  if(a == 1 and b == 1):
    return 1
  else:
    return 0

def Or (a,b):
  if(a == 1 or b == 1):
    return 1
  else:
    return 0
def Xor (a,b):
  nota = Not(a)
  notb = Not(b)
  aAndNotb = And(a,notb)
  notaAndb = And(nota,b)
  return Or(aAndNotb,notaAndb)

def HalfAdder(a, b):
    # Suma: XOR de a y b
    sum_bit = Xor(a, b)

    # Acarreo: AND de a y b
    carry_bit = And(a, b)

    return sum_bit, carry_bit

"""

```
Tabla de Verdad del Half Adder
| a | b | Suma (sum_bit) | Acarreo (carry_bit) |
|---|---|----------------|---------------------|
| 0 | 0 |        0        |         0          |
| 0 | 1 |        1        |         0          |
| 1 | 0 |        1        |         0          |
| 1 | 1 |        0        |         1          |
```

"""

def FullAdder(a, b, carry_in):
    # Suma parcial (a + b)
    sum_temp, carry_temp1 = HalfAdder(a, b)

    # Suma final (sum_temp + carry_in)
    sum_bit, carry_temp2 = HalfAdder(sum_temp, carry_in)

    # Acarreo final (carry_temp1 OR carry_temp2)
    carry_out = Or(carry_temp1, carry_temp2)

    return sum_bit, carry_out

def Add16(a, b):
    result = []
    carry = 0

    # Suma bit por bit (de derecha a izquierda)
    for i in range(15, -1, -1):
        sum_bit, carry = FullAdder(a[i], b[i], carry)
        result.insert(0, sum_bit)  # Insertar al inicio para mantener el orden

    return result

def Inc16(a):
    # Crear un número de 16 bits con valor 1
    one = [0] * 15 + [1]

    # Sumar 1 al número de entrada
    return Add16(a, one)

def ALU(x, y, zx, nx, zy, ny, f, no):
    # Control de la entrada x
    print("\n=== ALU ===")
    if zx == 1:  # Zero x
        x = [0] * 16
        print("(all zero X):", x)
    if nx == 1:  # Negate x
        x = [Not(bit) for bit in x]
        print("(negate x):", x)
    # Control de la entrada y

    if zy == 1:  # Zero y
        y = [0] * 16
        print("(all zero Y):", y)
    if ny == 1:  # Negate y
        y = [Not(bit) for bit in y]
        print("(negate y):", y)

    # Operación
    if f == 1:  # Add operation
        out = Add16(x, y)
        print(f"After ADD (x + y): {out}")
    if f == 0:  # AND operation
        out = [And(x[i], y[i]) for i in range(16)]
        print(f"After AND (x & y): {out}")

    # Negación final
    if no == 1:
        out = [Not(bit) for bit in out]

    # Flags
    zr = 1 if all(bit == 0 for bit in out) else 0
    ng = out[0]  # MSB indicates negative in two's complement

    return out, zr, ng

"""Este resultado por el two's complement


```
Decimal     | 16-bit Binary           | Two's Complement
------------------------------------------------------------
     7      | 0000000000000111        | 0000000000000111
     6      | 0000000000000110        | 0000000000000110
     5      | 0000000000000101        | 0000000000000101
     4      | 0000000000000100        | 0000000000000100
     3      | 0000000000000011        | 0000000000000011
     2      | 0000000000000010        | 0000000000000010
     1      | 0000000000000001        | 0000000000000001
     0      | 0000000000000000        | 0000000000000000
    -1      | 0000000000000001        | 1111111111111111
    -2      | 0000000000000010        | 1111111111111110
    -3      | 0000000000000011        | 1111111111111101
    -4      | 0000000000000100        | 1111111111111100
    -5      | 0000000000000101        | 1111111111111011
    -6      | 0000000000000110        | 1111111111111010
    -7      | 0000000000000111        | 1111111111111001
    -8      | 0000000000001000        | 1111111111111000
    ```


"""