# -*- coding: utf-8 -*-
"""Proyecto4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZPiE4koA0SFTWKyjCB6j1wlnaxwzH3L

Proyecto 4 NAND2TETRIS



Machine Language

Binary Code

Controla CPU, Registros y Memoria

Hack Computer Arquitecture

16-bit computer

CPU with ALU

Two Registers

A (Address Register) -> Hold memory and addresses

D (Data Register) -> Used for calculation

Memory Modules

ROM -> Program Instruction

RAM -> Read – Write Memory

Input / Output

Screen

Keyboard

Instructions

A – instruction (@value)

C – instruction (dest = comp; jump)

A – Instruction

Load 15-bit value

0 v v v v v v v v v v v v v v v  -> Binary representation 0 indicates A - Instruction

Load Constans into A- Instruction

Point memory addresses

Set up jumps for program flow

C – Instruction

Performs computations, memory access, and jumps.

Can compute values, store results, or control the flow of the program.

comp

Specifies the computation (like D+M, !D, A-1)

D+M

dest

Specifies where to store the result (A, D, M)

D=A

jump

Determines conditional/unconditional jumps

JGT

1 1 1 a c c c c c c d d d j j j  -> The first three bits (111) indicate a C-instruction

Memory Access  M Register  (Memory Register)

RAM has 32k memory (0 to 32767)

A- Instruction is used to access memory

The M register refers to RAM[A]

If A=100, then M means RAM[100]



Examples



//** Store 5 in RAM[10]



// Load address 10

@10

// Store value 5 at RAM[10]

M=5



//**  Copy Value from RAM[20] to RAM[30]



// Load address 20

@20

D=M   // D = RAM[20]

// Load address 30

@30

M=D   // RAM[30] = D



Control Flow (Jump Instructions) Solo 7 jumps

JGT (Jump if greater than 0)

JGE (Jump if greater than or equal to 0)

JLT (Jump if less than 0)

JLE (Jump if less than or equal to 0)

JEQ (Jump if equal to 0)

JNE (Jump if not equal to 0)

JMP (Unconditional jump)
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount("/content/drive/")

# Verificar que la carpeta existe
!ls "/content/drive/MyDrive/"

# Instalar import-ipynb
!pip install import-ipynb

# Cambiar a la carpeta correcta
# %cd "/content/drive/MyDrive/Colab Notebooks/Trabajos U/"

# Importar archivos IPYNB
import import_ipynb
import Proyecto2  # Importar funciones desde Proyecto2.ipynb
import Proyecto3  # Importar funciones desde Proyecto3.ipynb

import Proyecto2  # Importar funciones desde Proyecto2.ipynb
import Proyecto3  # Importar funciones desde Proyecto3.ipynb

from Proyecto2 import ALU, Add16, And, Or, Not, Xor, FullAdder, Inc16
from Proyecto3 import Register, PC, RAM64K

class CPU:
    def __init__(self):
        self.A = Register() #registro 16 bits
        self.D = Register() #registro 16 bits
        self.PC = PC()      # program counter
              # funcion ALU

    def execute(self, instruction, memory): # Funcion ejecutar, parametros instruccion y memoria, Instruccion registro de 16 bits, Memoria es RAM
        """Ejecuta una instrucción Hack."""
        print(f"Instrucción recibida: {instruction}")
        print(f"Primeros 3 bits de la instrucción: {instruction[:3]}")
        if instruction[0] == 0:  # A-instruction  # Si empieza con cero la instruccion 0 v v v ... se guarda el valor en registro A
            self.A.update(instruction, 1)
            print(f"Procesando A-instruction: {instruction}")
            self.PC.update([0]*16, 1, 0, 0)
            print(f"Salta ciclo de reloj a: {self.PC.update([0]*16, 0, 0, 0) }")

        if instruction[0] == 1 and instruction[1] == 1 and instruction[2] == 1:  # C-instruction de aritmetico logicas  # Si empieza con 1 la instruccion 1 v v v...
            print("Procesando C-instruction")
            comp = instruction[4:10]  # Bits de cómputo
            dest = instruction[10:13]  # Bits de destino
            jump = instruction[13:16]  # Bits de salto

            print(f"comp: {comp}, dest: {dest}, jump: {jump}")
            print(f"comp:{comp[0]},{comp[1]},{comp[2]},{comp[3]},{comp[4]},{comp[5]}")

            x = self.D.update([0]*16, 0)  # Guarda el Valor de D (Data Register)
            a_value = self.A.update([0]*16, 0)
            if(instruction[3] == 0):
              y = a_value  # y es igual a la instruccion A
              print(f"y toma el valor de A: {y}")
            if(instruction[3] == 1):
              y = memory.update([0]*16, 0, a_value)  # Guarda el valor de la memoria con direccion A, y = M[A]
              print(f"y toma el valor de la memoria con direccion A M[A]: {y}")

            # Ejecutar la ALU con los valores de entrada x (D) e y (memoria[A])
            result, zr, ng = ALU(x, y, comp[0],comp[1],comp[2],comp[3],comp[4],comp[5])   # se opera el registro D con el registro almancenado en memoria con direccion A

            print(f"ALU result: {result}, Zero flag: {zr}, Negative flag: {ng}")

            # Se verifica cual es el registro de destino

            if dest[0]:
              self.A.update(result, 1)  # dest[0] == 1 → Guardar en A
            if dest[1]:
              self.D.update(result, 1)  # dest[1] == 1 → Guardar en D
            if dest[2]:
              memory.update(result, 1, self.A.update([0]*16, 0)) # dest[2] == 1 → Guardar en la memoria en la dirección A

            if (jump[0] and ng) or (jump[1] and zr) or (jump[2] and not zr):  # jump[0] == 1 → Saltar si el resultado es negativo (ng == 1). # jump[1] == 1 → Saltar si el resultado es cero (zr == 1).  # jump[2] == 1 → Saltar si el resultado no es cero (zr == 0).
                print(f"Saltar a {self.A.update([0]*16, 0)}")
                self.PC.update(self.A.update([0]*16, 0), 0, 1, 0)             # Si se cumple alguna de estas condiciones, se actualiza el contador de programa (PC) con el valor de A:
            else:

                self.PC.update([0]*16, 1, 0, 0)                               # Si no se cumple la condición de salto, el PC simplemente se incrementa para ejecutar la siguiente instrucción secuencialmente:
                print(f"No se cumplio la condicion de salto, siguiente contador: {self.PC.update([0]*16, 0, 0, 0) }")

"""Ejemplo de ejecución en la CPU Hack

Supongamos que queremos ejecutar las siguientes instrucciones:

@5 → Cargar 5 en el registro A.

D=A → Copiar A en D.

@10 → Cargar 10 en A.

D=D+A → Sumar D + A y guardar en D.

@100 → Cargar 100 en A.

M=D → Guardar D en memoria[A] (posición 100).
"""

class HackComputer:
    def __init__(self):
        self.cpu = CPU()
        self.memory = RAM64K()
        self.rom = RAM64K()

    def load_program(self, program):
        """Carga un programa en la ROM."""  # Itera el programa a ejecutar
        for i, instruction in enumerate(program):
            address = [int(x) for x in format(i, '016b')]
            print(f"Cargando en ROM{[int(x) for x in format(i, '016b')]}: {instruction}")
            self.rom.update(instruction, 1, address)   #Lo guarda en la ROM


    def run(self):
        """Ejecuta el programa almacenado en ROM."""
        while True:
            address = self.cpu.PC.update([0]*16, 0, 0, 0) # Obtiene la dirección de la próxima instrucción desde PC (Program Counter).
            instruction = self.rom.update([0]*16, 0, address) # Recupera la instrucción almacenada en rom[address].
            print(f"\n Ejecutando instrucción en ROM[{address}]: {instruction}")  # Depuración
            if instruction == [1]*16:  # Opcional: usar una convención para HALT
               print("Programa finalizado (HALT).")
               break
            self.cpu.execute(instruction, self.memory) # Ejecuta la instrucción con self.cpu.execute(instruction, self.memory).
            print(f"Después de ejecutar: A={self.cpu.A.update([0]*16, 0)}, D={self.cpu.D.update([0]*16, 0)}, Memoria con Address A={self.memory.update([0]*16, 0, self.cpu.A.update([0]*16, 0))}")

# X es el registro D actulizado
# Y es el registro A o M[A]

program = [
    [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1],  # "@5" Empieza por cero guarda el valor en el registro A
    [1,1,1,0,1,1,0,0,0,0,0,1,0,0,0,0],  # D=A  Empieza por 1, Registro de computo ALU (X, Y , x = [0] * 16, x = [Not(bit) for bit in x],  y = [0] * 16, y = [Not(bit) for bit in y], ADD, AND , NEGAR SALIDA)
    [0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0],  # "@10"  Empieza por cero guarda el valor en el registro A
    [1,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0],  # D=D+A
    [0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0],  # "A = @100"
    [1,1,1,0,0,0,1,1,0,0,0,0,1,0,0,0],  # M=D  A = 100 -> D = 100, para despues
    [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]   # HALT
]

computer = HackComputer()
computer.load_program(program)
computer.run()

print("\nDespués de ejecutar el programa:")
print(f"A: {computer.cpu.A.update([0]*16, 0)} : ")
print(f"D: {computer.cpu.D.update([0]*16, 0)}")
print(f"Memoria con Address A: {computer.memory.update([0]*16, 0, computer.cpu.A.update([0]*16, 0))}")

# Programa 2 para multiplicacion de dos numeros y desplegar inputs como el teclado usando ASCII