# -*- coding: utf-8 -*-
"""Proyecto5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3GTRS0ocr45NaufOUmrASLi-iTIBWKj
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# from google.colab import drive
# drive.mount("/content/drive/")
# 
# # Verificar que la carpeta existe
# !ls "/content/drive/MyDrive/"
# 
# # Instalar import-ipynb
# !pip install import-ipynb
# 
# # Cambiar a la carpeta correcta
# %cd "/content/drive/MyDrive/Colab Notebooks/Trabajos U/"
# 
# # Importar archivos IPYNB
# import import_ipynb
# import Proyecto2  # Importar funciones desde Proyecto2.ipynb
# import Proyecto3  # Importar funciones desde Proyecto3.ipynb

import Proyecto2  # Importar funciones desde Proyecto2.ipynb
import Proyecto3  # Importar funciones desde Proyecto3.ipynb

from Proyecto2 import ALU, Add16, And, Or, Not, Xor, FullAdder, Inc16
from Proyecto3 import Register, PC, RAM64K, RAM16K

class CPU:
    def __init__(self):
        self.A = Register() #registro 16 bits
        self.D = Register() #registro 16 bits
        self.PC = PC()      # program counter
              # funcion ALU

    def execute(self, instruction, memory): # Funcion ejecutar, parametros instruccion y memoria, Instruccion registro de 16 bits, Memoria es RAM
        """Ejecuta una instrucción Hack."""
        print(f"Instrucción recibida: {instruction}")
        print(f"Primeros 3 bits de la instrucción: {instruction[:3]}")
        if instruction[0] == 0:  # A-instruction  # Si empieza con cero la instruccion 0 v v v ... se guarda el valor en registro A
            self.A.update(instruction, 1)
            print(f"Procesando A-instruction: {instruction}")
            self.PC.update([0]*16, 1, 0, 0)
            print(f"Salta ciclo de reloj a: {self.PC.update([0]*16, 0, 0, 0) }")

        if instruction[0] == 1 and instruction[1] == 1 and instruction[2] == 1:  # C-instruction de aritmetico logicas  # Si empieza con 1 la instruccion 1 v v v...
            print("Procesando C-instruction")
            comp = instruction[4:10]  # Bits de cómputo
            dest = instruction[10:13]  # Bits de destino
            jump = instruction[13:16]  # Bits de salto

            print(f"comp: {comp}, dest: {dest}, jump: {jump}")
            print(f"comp:{comp[0]},{comp[1]},{comp[2]},{comp[3]},{comp[4]},{comp[5]}")

            x = self.D.update([0]*16, 0)  # Guarda el Valor de D (Data Register)
            a_value = self.A.update([0]*16, 0)
            if(instruction[3] == 0):
              y = a_value  # y es igual a la instruccion A
              print(f"y toma el valor de A: {y}")
            if(instruction[3] == 1):
              y = memory.update([0]*16, 0, a_value)  # Guarda el valor de la memoria con direccion A, y = M[A]
              print(f"y toma el valor de la memoria con direccion A M[A]: {y}")

            # Ejecutar la ALU con los valores de entrada x (D) e y (memoria[A])
            result, zr, ng = ALU(x, y, comp[0],comp[1],comp[2],comp[3],comp[4],comp[5])   # se opera el registro D con el registro almancenado en memoria con direccion A

            print(f"ALU result: {result}, Zero flag: {zr}, Negative flag: {ng}")

            # Se verifica cual es el registro de destino

            if dest[0]:
              self.A.update(result, 1)  # dest[0] == 1 → Guardar en A
            if dest[1]:
              self.D.update(result, 1)  # dest[1] == 1 → Guardar en D
            if dest[2]:
              memory.update(result, 1, self.A.update([0]*16, 0)) # dest[2] == 1 → Guardar en la memoria en la dirección A

            if (jump[0] and ng) or (jump[1] and zr) or (jump[2] and not zr):  # jump[0] == 1 → Saltar si el resultado es negativo (ng == 1). # jump[1] == 1 → Saltar si el resultado es cero (zr == 1).  # jump[2] == 1 → Saltar si el resultado no es cero (zr == 0).
                print(f"Saltar a {self.A.update([0]*16, 0)}")
                self.PC.update(self.A.update([0]*16, 0), 0, 1, 0)             # Si se cumple alguna de estas condiciones, se actualiza el contador de programa (PC) con el valor de A:
            else:

                self.PC.update([0]*16, 1, 0, 0)                               # Si no se cumple la condición de salto, el PC simplemente se incrementa para ejecutar la siguiente instrucción secuencialmente:
                print(f"No se cumplio la condicion de salto, siguiente contador: {self.PC.update([0]*16, 0, 0, 0) }")

class HackComputer:
    def __init__(self):
        self.cpu = CPU()
        self.memory = RAM64K()
        self.rom = RAM64K()

    def load_program(self, program):
        """Carga un programa en la ROM."""  # Itera el programa a ejecutar
        for i, instruction in enumerate(program):
            address = [int(x) for x in format(i, '016b')]
            print(f"Cargando en ROM{[int(x) for x in format(i, '016b')]}: {instruction}")
            self.rom.update(instruction, 1, address)   #Lo guarda en la ROM


    def run(self):
        """Ejecuta el programa almacenado en ROM."""
        while True:
            address = self.cpu.PC.update([0]*16, 0, 0, 0) # Obtiene la dirección de la próxima instrucción desde PC (Program Counter).
            instruction = self.rom.update([0]*16, 0, address) # Obtiene la instrucción almacenada en rom[address].
            print(f"\n Ejecutando instrucción en ROM[{address}]: {instruction}")  # Depuración
            if instruction == [1]*16:  # Opcional: usar una convención para HALT
               print("Programa finalizado (HALT).")
               break
            self.cpu.execute(instruction, self.memory) # Ejecuta la instrucción con self.cpu.execute(instruction, self.memory).
            print(f"Después de ejecutar: A={self.cpu.A.update([0]*16, 0)}, D={self.cpu.D.update([0]*16, 0)}, Memoria con Address A={self.memory.update([0]*16, 0, self.cpu.A.update([0]*16, 0))}")

class Memory:
    def __init__(self):
        self.ram = RAM16K()       # Memoria principal (0-16383)
        self.screen = Screen()    # Mapa de memoria de pantalla (16384-24575)
        self.keyboard = Keyboard() # Registro de teclado (24576)

    def update(self, data, load, address):
        """
        Actualiza/lee la memoria según la dirección.

        Args:
            data: Valor de 16 bits a escribir (lista)
            load: 1 para escribir, 0 para leer
            address: Dirección (entero o lista de bits)

        Returns:
            Valor leído de la memoria (lista de 16 bits)
        """
        # Convertir address a entero si es una lista de bits
        if isinstance(address, list):
            address = self._bits_to_int(address)

        # Determinar qué componente acceder
        if address < 16384:  # RAM16K
            return self._handle_ram(data, load, address)
        elif address < 24576:  # Screen
            return self._handle_screen(data, load, address - 16384)
        elif address == 24576:  # Keyboard
            return self._handle_keyboard(data, load)
        else:
            print(f"Error: Dirección inválida {address}")
            return [0]*16

    def _bits_to_int(self, bits):
        """Convierte lista de bits a entero"""
        return int(''.join(map(str, bits)), 2)

    def _handle_ram(self, data, load, address):
        """Maneja acceso a RAM16K"""
        # RAM16K espera dirección como lista de 14 bits
        if isinstance(address, int):
            address = [int(x) for x in f"{address:014b}"]
        return self.ram.update(data, load, address)

    def _handle_screen(self, data, load, address):
        """Maneja acceso a Screen"""
        # Screen usa dirección entera
        if isinstance(address, list):
            address = self._bits_to_int(address)
        return self.screen.update(data, load, address)

    def _handle_keyboard(self, data, load):
        """Maneja acceso a Keyboard"""
        if load:
            print("Warning: Keyboard es de solo lectura")
        return self.keyboard.update([0]*16, 0)

class Screen:
    def __init__(self):
        # 8K words = 8192 registros de 16 bits
        self.memory = [[0]*16 for _ in range(8192)]

    def update(self, data, load, address):
        """Actualiza/lee la memoria de pantalla"""
        # Asegurarse de que address es entero
        if isinstance(address, list):
            address = int(''.join(map(str, address)), 2)

        if address < 0 or address >= 8192:
            print(f"Error: Dirección de pantalla inválida {address}")
            return [0]*16

        if load:
            self.memory[address] = data.copy()
        return self.memory[address].copy()

class Keyboard:
    def __init__(self):
        self.key_code = [0]*16  # Almacena código ASCII de la última tecla

    def update(self, data, load):
        """Solo lectura - devuelve el código de tecla actual"""
        return self.key_code.copy()

    def set_key(self, key_code):
        """Simula presión de tecla (para pruebas)"""
        self.key_code = [int(x) for x in format(key_code, '016b')]